### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by keivan68** [vita-epfl/monoloco#31]
Hi,

When I want to run the model on NVIDIA Jetson Nano GPU device, it turns this error:

python -m monoloco.run predict --predict --glob "data/input/*.png" --networks monoloco --output_type front bird --model data/models/monoloco-191018-1459.pkl -o data/output --z_max 22
/home/pyimagesearch/.virtualenvs/py3cv4/lib/python3.6/site-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'openpifpaf.network.nets.Shell' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
INFO:root:selected decoder: PifPaf
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pyimagesearch/Downloads/monoloco/monoloco/run.py", line 166, in <module>
    main()
  File "/home/pyimagesearch/Downloads/monoloco/monoloco/run.py", line 109, in main
    predict.predict(args)
  File "/home/pyimagesearch/Downloads/monoloco/monoloco/predict.py", line 19, in predict
    monoloco = MonoLoco(model=args.model, device=args.device, n_dropout=args.n_dropout, p_dropout=args.dropout)
  File "/home/pyimagesearch/Downloads/monoloco/monoloco/network/net.py", line 50, in __init__
    self.model.to(self.device)
  File "/home/pyimagesearch/.virtualenvs/py3cv4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/pyimagesearch/.virtualenvs/py3cv4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/pyimagesearch/.virtualenvs/py3cv4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/pyimagesearch/.virtualenvs/py3cv4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal

**Comment by bertoni9** [comment]
Hello,
Yes, CUDA was looking for a second gpu, as by default there was _cuda:1_. It should be solved now, let me know if it's not the case.
Best,
Lorenzo
