### ISSUE TITLE
Assertion Issue

### ISSUE THREAD

**Issue by digs1998** [vita-epfl/monoloco#81]
I get this issue after running the predict.py command using the webcam argument.

Using model: monoloco_pp-201207-1350.pkl
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/c/f006d3c/.conda/envs/mytest/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dartfs-hpc/rc/home/c/f006d3c/.conda/envs/mytest/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/dartfs-hpc/rc/home/c/f006d3c/monoloco/monoloco/run.py", line 218, in <module>
    main()
  File "/dartfs-hpc/rc/home/c/f006d3c/monoloco/monoloco/run.py", line 144, in main
    webcam(args)
  File "/dartfs-hpc/rc/home/c/f006d3c/monoloco/monoloco/visuals/webcam.py", line 80, in webcam
    args, dic_models = factory_from_args(args)
  File "/dartfs-hpc/rc/home/c/f006d3c/monoloco/monoloco/visuals/webcam.py", line 38, in factory_from_args
    assert len(args.output_types) == 1 and 'json' not in args.output_types
AssertionError

**Comment by dimarapis** [comment]
If still interested, you need to parse --output_types multi (e.g. python3 -m monoloco.run predict --webcam --output_types multi )  or remove assertion. Also, you will probably need to install matplotlib 3.4.1 (pip install matplotlib==3.4.1).
